# Generated by Django 3.1.7 on 2023-06-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230322_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='num_rows',
            field=models.IntegerField(verbose_name='Количество строк'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
